name:                fsnotify
version:             0.4.4.0
license:             BSD3
license-file:        LICENSE
author:              Mark Dittmer <mark.s.dittmer@gmail.com>, Niklas Broberg
maintainer:          Tom McLaughlin <tom@codedown.io>
category:            Filesystem
homepage:            https://github.com/haskell-fswatch/hfsnotify
synopsis:            Cross platform library for file change notification.
description:         Cross platform library for file creation, modification, and deletion notification. This library builds upon existing libraries for platform-specific Windows, Mac, and Linux filesystem event notification.

extra-source-files:
- README.md
- CHANGELOG.md
- test/Main.hs

when:
- condition: os(linux) || os(windows) || os(darwin) || os(freebsd)
  cpp-options: -DHAVE_NATIVE_WATCHER

default-extensions:
- ScopedTypeVariables

library:
  source-dirs: src

  other-modules:
  - System.FSNotify.Find
  - System.FSNotify.Listener
  - System.FSNotify.Path
  - System.FSNotify.Polling
  - System.FSNotify.Types

  when:
  - condition: os(linux) || os(freebsd)
    other-modules:
    - System.FSNotify.Linux
    - System.FSNotify.Linux.Util
    dependencies:
    - unix >= 2.7.1.0
  - condition: os(linux) && impl(ghc >= 9.10)
    dependencies:
    # hinotify-0.4.2 fixed support for GHC 9.10
    - hinotify >= 0.4.2
  - condition: os(linux) && impl(ghc < 9.10)
    dependencies:
    # hinotify-0.3.9 has some bugfixes we should insist upon
    - hinotify >= 0.3.9

  - condition: os(windows)
    source-dirs: win-src
    other-modules:
    - System.FSNotify.Win32
    - System.Win32.FileNotify
    - System.Win32.Notify
    dependencies: Win32

  - condition: os(darwin)
    other-modules:
    - System.FSNotify.OSX
    # hfsevents-0.1.8 fixed a race condition in the watch setup
    dependencies: hfsevents >= 0.1.8

  - condition: os(freebsd)
    dependencies: hinotify >= 0.4.1

  dependencies:
  - async >= 2.0.0.0
  - base >= 4.8 && < 5
  - bytestring >= 0.10.2
  - containers >= 0.4
  - directory >= 1.3.0.0
  - filepath >= 1.3.0.0
  - monad-control >= 1.0.0.0
  - safe-exceptions >= 0.1.0.0
  - text >= 0.11.0 && < 2.2
  - time >= 1.1
  - unix-compat >= 0.2
  ghc-options:
  - -Wall
  exposed-modules:
    - System.FSNotify
    - System.FSNotify.Devel


executables:
  example:
    main: Main.hs
    source-dirs:
    - example
    ghc-options:
    - -Wall
    when:
    - condition: '!arch(wasm32)'
      ghc-options:
      - -threaded
    dependencies:
    - base
    - directory
    - exceptions
    - filepath
    - fsnotify
    - monad-logger
    - random
    - retry
    - safe-exceptions
    - string-interpolate
    - temporary
    - unix-compat
    - unliftio

tests:
  tests:
    main: Main.hs
    source-dirs:
    - test
    ghc-options:
    - -threaded
    - -Wall
    dependencies:
    - async >= 2
    - base >= 4.3.1.0
    - directory
    - exceptions
    - filepath
    - fsnotify
    - monad-logger
    - random
    - retry
    - safe-exceptions
    - string-interpolate
    - temporary
    - unix-compat
    - unliftio >= 0.2.20
    when:
    - condition: os(windows)
      then:
        dependencies:
        - Win32
        - sandwich >= 0.1.1.1 # Earliest version to support windows
      else:
        dependencies:
        - sandwich
